# fly.toml — cấu hình chạy bot kiểu worker (không cần HTTP)
app = "bottele-s0gg-q"   # <--- đổi đúng tên app trên Fly
primary_region = "sin"   # chọn region gần bạn: sin, hkg, nrt, bom, syd,...

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python tele_fb_monitor1.py"

# Không có [[services]] => không có HTTP/port/healthcheck
# Nếu Fly đã sinh [[services]] trước đó, file này sẽ ghi đè và bỏ hết.