app = "bottele" # đổi thành tên app của bạn trên Fly.io

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  cmd = ["python", "tele_fb_monitor1.py"]

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
