app = "bottele-s0gg-q"   # đúng tên app của bạn trên Fly.io
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python tele_fb_monitor1.py"
